services:
  web-api:
    image: hypermsg.scada.webapi
    build:
      context: Backend/HyperMsg.Scada.WebApi/
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development